language: ruby
matrix:
  include:
  - rvm: "2.4"
  - rvm: "2.3"
  - rvm: "2.2"
  - rvm: "2.1"
  - env: RACK_VERSION="~> 2.0.1"
  - env: RACK_VERSION="~> 1.6.0"
  - env: RACK_VERSION="~> 1.5.0"
  - env: RACK_VERSION="~> 1.4.0"
  - env: RACK_VERSION="~> 1.3.0"
